# Generated by Django 4.0.4 on 2022-04-15 08:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('childrenNames', django_mysql.models.ListTextField(models.CharField(max_length=30), size=5)),
                ('pointNumbers', models.JSONField()),
                ('numberArrays', models.JSONField()),
            ],
        ),
    ]
